Added method `new_blockquote`
IgnisDa/python-random-markdown-generator pull request #10
Opened 2020-10-04 08:24 UTC by parthpandyappp

## Description of new pull request

**Files Added** -  1
**Issue No.**- #6 

## Checklist(self check):

- [x] My code follows the style guidelines(Clean Code) of this project
- [x] I have performed a self-review of my own code

Hope this fixes the issue.

2020-10-04 23:03 UTC, IgnisDa commented on mdgen/core/blockquote.py
> +    """ This class converts an input string into a markdown
There is a whitespace at the end of this line. That needs to be deleted as it is causing the build to fail.

2020-10-04 23:04 UTC, IgnisDa requested changes
Please fix these issues

2020-10-05 08:13 UTC, parthpandyappp commented
Flake8 issues fixed!

2020-10-05 08:22 UTC, merged

2020-10-05 08:22 UTC, IgnisDa commented
Issue #6  fixed by @parthpandyappp . Thanks!